/**
 * 真实文件导出 / 保存 / 分享（iOS 原生）：
 *  - @capacitor/filesystem   → 真实写入本地 Documents / Cache（含父目录自动创建）
 *  - @capacitor/action-sheet → 下载完成后询问“在‘文件’中查看 / 发送分享”
 *  - @capacitor/share        → 原生 iOS Share Sheet（AirDrop / 存到“文件” / Telegram / 微信 / 打印）
 *  - jspdf                   → 动态生成标准 .pdf（资料离线副本 / 学业成绩单）
 *
 * 纯 Web 预览：原生接口不可用时，退回真实浏览器下载（Blob + <a download>）。
 */
import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";
import { ActionSheet, ActionSheetButtonStyle } from "@capacitor/action-sheet";
import { jsPDF } from "jspdf";

export const isNative = () => Capacitor.isNativePlatform();

/** 用户在“文件”App 中可见的下载目录（相对 Documents） */
export const APP_DOCS_FOLDER = "KazNU Helper/Downloads";

/** 供系统分享用的临时导出目录（相对 Cache，系统可自动清理） */
export const APP_TMP_FOLDER = "kaznu-helper/exports";

/** 把非 ASCII 排版符号换成可读 ASCII，保证 PDF / 文件名不出现乱码方块。 */
function pdfSafe(text: string): string {
  const aliases: Array<[RegExp, string]> = [
    [/[–—]/g, "-"],
    [/[·•]/g, " - "],
    [/[’‘]/g, "'"],
    [/[“”]/g, '"'],
    [/…/g, "..."],
    [/₸/g, "KZT"],
    [/≥/g, ">="],
    [/≤/g, "<="],
  ];
  let out = text;
  for (const [re, to] of aliases) out = out.replace(re, to);
  return out
    .replace(/[^\x20-\x7E]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** 文件名清洗：去掉 / : * ? " < > | 与非法尾点，返回可落盘的 basename（不含扩展名）。 */
export function sanitizeBaseName(name: string): string {
  return pdfSafe(name)
    .replace(/[\\/:*?"<>|]/g, "-")
    .replace(/[.\s]+$/g, "")
    .slice(0, 90);
}

export function toPdfFileName(base: string, suffix = ""): string {
  const clean = sanitizeBaseName(base) || "document";
  return suffix ? `${clean}-${suffix}.pdf` : `${clean}.pdf`;
}

/* ===================== jsPDF 生成器 ===================== */

const PAGE_W = 595; // A4 (pt)
const PAGE_H = 842;
const MARGIN = 46;

function drawFooter(doc: jsPDF, generatedAt: Date) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 128);
    const footer = `KazNU Helper - Al-Farabi Kazakh National University   |   ${generatedAt.toLocaleString("en-GB", { hour12: false })}`;
    doc.text(pdfSafe(footer), MARGIN, PAGE_H - 28);
    doc.text(`${i} / ${pages}`, PAGE_W - MARGIN, PAGE_H - 28, { align: "right" });
  }
}

/** 资料下载时生成的“离线副本”PDF（真实二进制 PDF，写入 Documents 供查看/分享）。 */
export function createMaterialPdf(meta: {
  course: string;
  code: string;
  prof: string;
  title: string;
  format: string;
  size: string;
  date: string;
}): string {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const now = new Date();

  // 顶部校徽色带
  doc.setFillColor(0, 51, 160);
  doc.rect(0, 0, PAGE_W, 128, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("AL-FARABI KAZAKH NATIONAL UNIVERSITY", MARGIN, 52);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("KazNU Helper - Offline Course Material", MARGIN, 76);
  doc.text(pdfSafe(meta.course), MARGIN, 100);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(pdfSafe(`${meta.code}  |  ${meta.prof}`), PAGE_W - MARGIN, 100, { align: "right" });

  // 标题区
  doc.setTextColor(28, 28, 30);
  doc.setFontSize(23);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(pdfSafe(meta.title), PAGE_W - MARGIN * 2) as string[];
  let y = 182;
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 28 + 8;
  doc.setDrawColor(220, 220, 224);
  doc.setLineWidth(1);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);

  // 元信息
  y += 34;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(70, 70, 74);
  const rows: Array<[string, string]> = [
    ["File format", meta.format],
    ["Displayed size", meta.size],
    ["Published date", meta.date],
    ["Generated by", "KazNU Helper (iOS)"],
  ];
  for (const [k, v] of rows) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 34);
    doc.text(k, MARGIN, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90, 90, 96);
    doc.text(pdfSafe(v), 190, y);
    y += 24;
  }

  y += 26;
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 128);
  const note = doc.splitTextToSize(
    pdfSafe(
      "This offline copy was generated locally by the KazNU Helper app and saved to your device Documents folder. It is intended for personal study use.",
    ),
    PAGE_W - MARGIN * 2,
  ) as string[];
  doc.text(note, MARGIN, y);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 51, 160);
  doc.setFontSize(12);
  doc.text("KazNU Helper", MARGIN, PAGE_H - 92);
  drawFooter(doc, now);
  return doc.output("datauristring").split(",")[1] ?? "";
}

export interface TranscriptCourseInput {
  name: string;
  grade: string;
  score: number;
  ects: number;
}

export interface TranscriptSemesterInput {
  label: string;
  gpa: number;
  credits: number;
  courses: TranscriptCourseInput[];
}

export interface TranscriptPdfInput {
  studentName?: string;
  studentId?: string;
  cumulativeGpa: number;
  honor?: string;
  rank?: string;
  earnedEcts: number;
  totalEcts: number;
  semesters: TranscriptSemesterInput[];
}

/** 学业成绩单 PDF：真实逐页表格排版，超页自动翻页 + 页脚页码。 */
export function createTranscriptPdf(input: TranscriptPdfInput): string {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const now = new Date();

  // ---- 页眉校徽色带 ----
  doc.setFillColor(0, 51, 160);
  doc.rect(0, 0, PAGE_W, 120, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("AL-FARABI KAZAKH NATIONAL UNIVERSITY", MARGIN, 46);
  doc.setFontSize(11);
  doc.text("Academic Record / Official Transcript", MARGIN, 70);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("KazNU Helper export", PAGE_W - MARGIN, 46, { align: "right" });
  doc.text(now.toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }), PAGE_W - MARGIN, 62, {
    align: "right",
  });

  // ---- 学生摘要 ----
  doc.setTextColor(28, 28, 30);
  let y = 156;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(pdfSafe(input.studentName ?? "Student") || "Student", MARGIN, y);
  if (input.studentId) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 106);
    doc.text(`Student ID: ${pdfSafe(input.studentId)}`, PAGE_W - MARGIN, y, { align: "right" });
  }

  // ---- GPA / 荣誉 / 学分概览 ----
  y += 30;
  doc.setFillColor(245, 246, 250);
  doc.roundedRect(MARGIN, y, PAGE_W - MARGIN * 2, 64, 8, 8, "F");
  const overview: Array<[string, string]> = [
    ["Cumulative GPA", `${input.cumulativeGpa.toFixed(2)} / 4.0`],
    ["Standing", input.honor ?? "-"],
    ["Rank", input.rank ?? "-"],
    ["ECTS", `${input.earnedEcts} / ${input.totalEcts}`],
  ];
  const colStart = MARGIN + 14;
  const colW = (PAGE_W - MARGIN * 2 - 28) / overview.length;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(110, 110, 118);
  overview.forEach((c, i) => {
    doc.text(c[0].toUpperCase(), colStart + i * colW, y + 20);
  });
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 26);
  overview.forEach((c, i) => {
    doc.text(c[1], colStart + i * colW, y + 42);
  });

  // ---- 逐学期成绩表 ----
  y += 96;
  const rowH = 24;
  const headH = 26;
  const pageBottom = PAGE_H - 56;
  const ensureSpace = (needed: number) => {
    if (y + needed > pageBottom) {
      doc.addPage();
      y = MARGIN + 6;
    }
  };

  for (const sem of input.semesters) {
    ensureSpace(headH + rowH * 3);
    // 学期标题行
    doc.setFillColor(240, 242, 248);
    doc.rect(MARGIN, y, PAGE_W - MARGIN * 2, headH, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 26);
    doc.text(pdfSafe(sem.label), MARGIN + 10, y + 17);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 96);
    doc.text(`${sem.credits} ECTS`, PAGE_W - MARGIN - 104, y + 17);
    doc.text(`GPA ${sem.gpa.toFixed(2)}`, PAGE_W - MARGIN - 14, y + 17, { align: "right" });
    y += headH;

    // 列头
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120, 120, 128);
    doc.text("COURSE", MARGIN + 10, y + 17);
    doc.text("ECTS", PAGE_W - MARGIN - 192, y + 17);
    doc.text("GRADE", PAGE_W - MARGIN - 126, y + 17);
    doc.text("SCORE", PAGE_W - MARGIN - 14, y + 17, { align: "right" });
    y += headH;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    for (const course of sem.courses) {
      const nameLines = doc.splitTextToSize(pdfSafe(course.name), 245) as string[];
      const cellH = Math.max(rowH, nameLines.length * 13 + 12);
      ensureSpace(cellH + 2);
      doc.setTextColor(28, 28, 30);
      doc.setFont("helvetica", "bold");
      doc.text(nameLines, MARGIN + 10, y + 14);
      doc.setFont("helvetica", "normal");
      doc.text(String(course.ects), PAGE_W - MARGIN - 192, y + 14);
      doc.text(pdfSafe(course.grade), PAGE_W - MARGIN - 126, y + 14);
      doc.text(`${course.score}%`, PAGE_W - MARGIN - 14, y + 14, { align: "right" });
      doc.setDrawColor(235, 235, 240);
      doc.setLineWidth(0.7);
      doc.line(MARGIN + 6, y + cellH - 4, PAGE_W - MARGIN - 6, y + cellH - 4);
      y += cellH;
    }
    y += 16;
  }

  // ---- 文末说明 ----
  doc.setTextColor(110, 110, 118);
  doc.setFontSize(8);
  const legend =
    "This document was generated automatically by the KazNU Helper mobile app from locally available academic data. ECTS: European Credit Transfer System.";
  const legendLines = doc.splitTextToSize(pdfSafe(legend), PAGE_W - MARGIN * 2) as string[];
  ensureSpace(legendLines.length * 11 + 20);
  doc.text(legendLines, MARGIN, y);

  drawFooter(doc, now);
  return doc.output("datauristring").split(",")[1] ?? "";
}

/* ===================== Filesystem 写入 / 删除 ===================== */

export interface SavedFileResult {
  fileName: string;
  /** 原生 file:// 绝对 URI（可直接喂给 Share） */
  uri: string;
  /** 相对目录的路径 */
  relativePath: string;
}

/**
 * 把 base64 的 PDF 真实写入本地目录（仅原生端调用）。
 * - dir=Documents → 持久保存（配合 Info.plist UIFileSharingEnabled，
 *   用户可在“文件 → 我的 iPhone → KazNU Helper”中看到）；
 * - dir=Cache     → 临时导出，供系统分享 Sheet 读取。
 */
export async function writePdfFile(
  base64: string,
  fileName: string,
  options: { dir?: Directory; folder?: string } = {},
): Promise<SavedFileResult> {
  const directory = options.dir ?? Directory.Documents;
  const folder = options.folder ?? APP_DOCS_FOLDER;
  const relativePath = folder ? `${folder}/${fileName}` : fileName;
  const result = await Filesystem.writeFile({
    path: relativePath,
    data: base64,
    directory,
    recursive: true,
  });
  return { fileName, uri: result.uri, relativePath };
}

/** 删除 Documents 里已保存的文件（点击“移除”时回收磁盘空间）。 */
export async function deleteSavedPdf(fileName: string): Promise<void> {
  try {
    await Filesystem.deleteFile({ path: `${APP_DOCS_FOLDER}/${fileName}`, directory: Directory.Documents });
  } catch {
    /* 文件不存在等情况静默 */
  }
}

/* ===================== 原生 Action Sheet / Share Sheet ===================== */

export type AfterSaveChoice = "view" | "share" | "dismiss";

/**
 * 下载 / 生成完成后弹原生 Action Sheet，让用户选择：
 *  - 在“文件”中查看（文件已写入 Documents，并告知精确位置）
 *  - 发送 / 分享（打开系统 Share Sheet）
 * 非原生平台直接返回 "dismiss"。
 */
export async function askAfterSave(fileName: string): Promise<AfterSaveChoice> {
  if (!isNative()) return "dismiss";
  const result = await ActionSheet.showActions({
    title: `${fileName} 已完成`,
    message: "已保存到本地：文件 App → 我的 iPhone → KazNU Helper → Downloads",
    options: [
      { title: "在“文件”中查看", style: ActionSheetButtonStyle.Default },
      { title: "发送 / 分享…", style: ActionSheetButtonStyle.Default },
      { title: "取消", style: ActionSheetButtonStyle.Cancel },
    ],
  });
  if (result.canceled || result.index < 0) return "dismiss";
  if (result.index === 0) return "view";
  if (result.index === 1) return "share";
  return "dismiss";
}

/** 用 iOS 原生系统 Share Sheet 分享一个 file:// URI（存“文件”/微信/Telegram/打印都在其中）。 */
export async function shareNativeFile(uri: string, opts: { title?: string; text?: string } = {}): Promise<void> {
  await Share.share({
    files: [uri],
    dialogTitle: "KazNU Helper",
    title: opts.title,
    text: opts.text,
  });
}

/* ===================== Web 真实下载（浏览器兜底） ===================== */

export function downloadBase64OnWeb(base64: string, fileName: string, mime = "application/pdf") {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  const blob = new Blob([bytes], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/**
 * 导出 PDF → 写入 Cache 临时目录 → 返回 file:// URI（紧接着交给系统 Share Sheet）。
 * 临时目录系统可回收，不会占用用户文档空间。
 */
export function exportPdfForSharing(base64: string, fileName: string): Promise<SavedFileResult> {
  return writePdfFile(base64, fileName, { dir: Directory.Cache, folder: APP_TMP_FOLDER });
}

/** 把 PDF 直接保存到 Documents（“文件 → 我的 iPhone → KazNU Helper”可见）。 */
export function savePdfToDocuments(base64: string, fileName: string): Promise<SavedFileResult> {
  return writePdfFile(base64, fileName);
}
